### PR TITLE
Allow anyone to top-up any staking provider with liquid T

### PR DESCRIPTION
**Pull request by vzotova**

### CODE REVIEW

**Review by theref — DISMISSED** [review]
Looks good!

**Review by manumonti — COMMENTED** [review]
LGTM! ✌️

**Review by manumonti — DISMISSED** [review]
LGTM! ✌️

**Review by cygnusv — DISMISSED** [review]

**Comment by pdyraga** [comment]
Some context for spectators and future us: this change will allow to top-up stake from the reward merkle distributor contract in a single transaction.

**Review by pdyraga — APPROVED** [review]

**Comment by cygnusv** [comment]
> Some context for spectators and future us: this change will allow to top-up stake from the reward merkle distributor contract in a single transaction.

And also, once we activate rewards distribution from application contracts, it will be possible to automatically top up from there.

**Pull request merged**
